// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvtGIWMqg8PxAXKnxYmcOmm-QsTGmlLoQ',
    appId: '1:67857742392:web:12ca0fb808169bb9ae44cd',
    messagingSenderId: '67857742392',
    projectId: 'mysocietyapp-b0ff5',
    authDomain: 'mysocietyapp-b0ff5.firebaseapp.com',
    storageBucket: 'mysocietyapp-b0ff5.firebasestorage.app',
    measurementId: 'G-2MW5BJ7S6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOr0xMPbXLyCzzsz46rDU-6OlM8UUTXNA',
    appId: '1:67857742392:android:c23b6a4ee2a40188ae44cd',
    messagingSenderId: '67857742392',
    projectId: 'mysocietyapp-b0ff5',
    storageBucket: 'mysocietyapp-b0ff5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_qkPcKCr3bBSKiQgCyYTm2ve_xbCJ7OQ',
    appId: '1:67857742392:ios:e4c0637d5f1b2204ae44cd',
    messagingSenderId: '67857742392',
    projectId: 'mysocietyapp-b0ff5',
    storageBucket: 'mysocietyapp-b0ff5.firebasestorage.app',
    iosBundleId: 'com.example.mysociety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_qkPcKCr3bBSKiQgCyYTm2ve_xbCJ7OQ',
    appId: '1:67857742392:ios:e4c0637d5f1b2204ae44cd',
    messagingSenderId: '67857742392',
    projectId: 'mysocietyapp-b0ff5',
    storageBucket: 'mysocietyapp-b0ff5.firebasestorage.app',
    iosBundleId: 'com.example.mysociety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvtGIWMqg8PxAXKnxYmcOmm-QsTGmlLoQ',
    appId: '1:67857742392:web:3ac45af8c42fed85ae44cd',
    messagingSenderId: '67857742392',
    projectId: 'mysocietyapp-b0ff5',
    authDomain: 'mysocietyapp-b0ff5.firebaseapp.com',
    storageBucket: 'mysocietyapp-b0ff5.firebasestorage.app',
    measurementId: 'G-XNBJFRL64M',
  );

}